### ISSUE TITLE
telak fails to compile under Debian bullseye

### ISSUE THREAD

**Issue by stsc** [jd/telak#2]
Tried compiling telak `v0.6` under Debian 11.1 (bullseye) without initial success.

Moving the linker flags to the end, omitting the inclusion of a header file twice and
inserting a function declaration made it work for me.

### Data:
GNU Make 4.3
Built for i686-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

cc (Debian 10.2.1-6) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Patch:
[https://paste.cerny.li/txk/](https://paste.cerny.li/txk/)

Let me know if you require more information.

Hope this helps,

**Comment by jd** [comment]
Merged your patch and tagged 0.7, thank you!
