### ISSUE TITLE
missing ChangeLog entry for v0.7

### ISSUE THREAD

**Issue by stsc** [jd/telak#3]
The subject says it all :-).

Hence the version being set is still `0.6`. It is extracted by following Makefile line:

`VERSION = $(shell grep '^Version' ChangeLog | head -n 1 | cut -d' ' -f2 | tr -d ' ')`

You can or even better should add an entry; furthermore, the tag for `v0.7` should be adjusted.

**Comment by jd** [comment]
Should be fine, I've force-pushed the tag.
